-- Delete all data from the dnbookstore.Books table
DELETE FROM dnbookstore.Books;

-- Delete all data from the dnbookstore.Authors table
DELETE FROM dnbookstore.Authors;

-- Insert sample data into the dnbookstore.Authors table
INSERT INTO dnbookstore.Authors (FirstName, LastName) VALUES
('F. Scott', 'Fitzgerald'),
('Harper', 'Lee'),
('George', 'Orwell'),
('Jane', 'Austen'),
('J.D.', 'Salinger'),
('J.R.R.', 'Tolkien'),
('Ray', 'Bradbury'),
('Herman', 'Melville'),
('Leo', 'Tolstoy'),
('', 'Homer'),
('Agatha', 'Christie'),
('J.K.', 'Rowling'),
('Mark', 'Twain'),
('Charles', 'Dickens'),
('Ernest', 'Hemingway'),
('Fyodor', 'Dostoevsky'),
('Gabriel', 'Garcia Marquez'),
('William', 'Shakespeare'),
('James', 'Joyce'),
('Virginia', 'Woolf'),
('H.G.', 'Wells'),
('Isaac', 'Asimov'),
('Arthur', 'Conan Doyle'),
('Edgar Allan', 'Poe'),
('Jules', 'Verne'),
('Kurt', 'Vonnegut'),
('George', 'Eliot'),
('John', 'Steinbeck'),
('Aldous', 'Huxley'),
('Franz', 'Kafka'),
('Lewis', 'Carroll'),
('Jack', 'London'),
('Haruki', 'Murakami'),
('Orhan', 'Pamuk'),
('Kazuo', 'Ishiguro'),
('Margaret', 'Atwood'),
('Chinua', 'Achebe'),
('Salman', 'Rushdie'),
('E.M.', 'Forster');

-- Insert additional books into the dnbookstore.Books table
INSERT INTO dnbookstore.Books (Title, Genre, PublishedDate, AuthorId, Price) VALUES
('The Great Gatsby', 'Fiction', '1925-04-10', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'F. Scott' AND LastName = 'Fitzgerald'), 10.99),
('To Kill a Mockingbird', 'Fiction', '1960-07-11', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Harper' AND LastName = 'Lee'), 7.99),
('1984', 'Dystopian', '1949-06-08', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'George' AND LastName = 'Orwell'), 8.99),
('Pride and Prejudice', 'Romance', '1813-01-28', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Jane' AND LastName = 'Austen'), 5.99),
('The Catcher in the Rye', 'Fiction', '1951-07-16', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.D.' AND LastName = 'Salinger'), 6.99),
('The Hobbit', 'Fantasy', '1937-09-21', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.R.R.' AND LastName = 'Tolkien'), 12.99),
('Fahrenheit 451', 'Dystopian', '1953-10-19', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Ray' AND LastName = 'Bradbury'), 9.99),
('Moby-Dick', 'Adventure', '1851-10-18', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Herman' AND LastName = 'Melville'), 11.99),
('War and Peace', 'Historical', '1869-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Leo' AND LastName = 'Tolstoy'), 14.99),
('The Odyssey', 'Epic', '800-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = '' AND LastName = 'Homer'), 13.99),
('Murder on the Orient Express', 'Mystery', '1934-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Agatha' AND LastName = 'Christie'), 9.99),
('Harry Potter and the Sorcerer''s Stone', 'Fantasy', '1997-06-26', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.K.' AND LastName = 'Rowling'), 8.99),
('The Adventures of Tom Sawyer', 'Fiction', '1876-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Mark' AND LastName = 'Twain'), 7.99),
('A Tale of Two Cities', 'Historical', '1859-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Charles' AND LastName = 'Dickens'), 8.99),
('The Old Man and the Sea', 'Fiction', '1952-09-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Ernest' AND LastName = 'Hemingway'), 6.99),
('Crime and Punishment', 'Fiction', '1866-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Fyodor' AND LastName = 'Dostoevsky'), 7.99),
('One Hundred Years of Solitude', 'Magical Realism', '1967-05-30', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Gabriel' AND LastName = 'Garcia Marquez'), 9.99),
('Hamlet', 'Tragedy', '1603-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'William' AND LastName = 'Shakespeare'), 5.99),
('Ulysses', 'Modernist', '1922-02-02', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'James' AND LastName = 'Joyce'), 10.99),
('Anna Karenina', 'Fiction', '1878-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Leo' AND LastName = 'Tolstoy'), 12.99),
('To the Lighthouse', 'Modernist', '1927-05-05', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Virginia' AND LastName = 'Woolf'), 7.99),
('The War of the Worlds', 'Science Fiction', '1898-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'H.G.' AND LastName = 'Wells'), 6.99),
('Foundation', 'Science Fiction', '1951-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Isaac' AND LastName = 'Asimov'), 8.99),
('Sherlock Holmes: A Study in Scarlet', 'Mystery', '1887-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Arthur' AND LastName = 'Conan Doyle'), 7.99),
('The Raven', 'Poetry', '1845-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Edgar Allan' AND LastName = 'Poe'), 4.99),
('Twenty Thousand Leagues Under the Sea', 'Science Fiction', '1870-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Jules' AND LastName = 'Verne'), 9.99),
('The Iliad', 'Epic', '800-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = '' AND LastName = 'Homer'), 11.99),
('The Silmarillion', 'Fantasy', '1977-09-15', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.R.R.' AND LastName = 'Tolkien'), 14.99),
('Slaughterhouse-Five', 'Science Fiction', '1969-03-31', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Kurt' AND LastName = 'Vonnegut'), 7.99),
('Middlemarch', 'Fiction', '1871-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'George' AND LastName = 'Eliot'), 9.99),
('Of Mice and Men', 'Fiction', '1937-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'John' AND LastName = 'Steinbeck'), 5.99),
('Brave New World', 'Dystopian', '1932-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Aldous' AND LastName = 'Huxley'), 6.99),
('The Metamorphosis', 'Fiction', '1915-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Franz' AND LastName = 'Kafka'), 7.99),
('Alice''s Adventures in Wonderland', 'Fantasy', '1865-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Lewis' AND LastName = 'Carroll'), 6.99),
('The Beautiful and Damned', 'Fiction', '1922-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'F. Scott' AND LastName = 'Fitzgerald'), 8.99),
('Go Set a Watchman', 'Fiction', '2015-07-14', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Harper' AND LastName = 'Lee'), 9.99),
('Animal Farm', 'Dystopian', '1945-08-17', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'George' AND LastName = 'Orwell'), 5.99),
('Sense and Sensibility', 'Romance', '1811-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Jane' AND LastName = 'Austen'), 7.99),
('Franny and Zooey', 'Fiction', '1961-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.D.' AND LastName = 'Salinger'), 6.99),
('The Martian Chronicles', 'Science Fiction', '1950-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Ray' AND LastName = 'Bradbury'), 8.99),
('White Fang', 'Adventure', '1906-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Jack' AND LastName = 'London'), 7.99),
('Norwegian Wood', 'Fiction', '1987-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Haruki' AND LastName = 'Murakami'), 8.99),
('My Name is Red', 'Historical', '1998-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Orhan' AND LastName = 'Pamuk'), 9.99),
('Never Let Me Go', 'Dystopian', '2005-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Kazuo' AND LastName = 'Ishiguro'), 10.99),
('The Handmaid''s Tale', 'Dystopian', '1985-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Margaret' AND LastName = 'Atwood'), 7.99),
('Things Fall Apart', 'Historical', '1958-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Chinua' AND LastName = 'Achebe'), 8.99),
('Midnight''s Children', 'Historical', '1981-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'Salman' AND LastName = 'Rushdie'), 9.99),
('A Passage to India', 'Fiction', '1924-01-01', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'E.M.' AND LastName = 'Forster'), 7.99),
('Harry Potter and the Chamber of Secrets', 'Fantasy', '1998-07-02', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.K.' AND LastName = 'Rowling'), 8.99),
('Harry Potter and the Prisoner of Azkaban', 'Fantasy', '1999-07-08', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.K.' AND LastName = 'Rowling'), 8.99),
('Harry Potter and the Goblet of Fire', 'Fantasy', '2000-07-08', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.K.' AND LastName = 'Rowling'), 9.99),
('Harry Potter and the Order of the Phoenix', 'Fantasy', '2003-06-21', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.K.' AND LastName = 'Rowling'), 9.99),
('Harry Potter and the Half-Blood Prince', 'Fantasy', '2005-07-16', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.K.' AND LastName = 'Rowling'), 9.99),
('Harry Potter and the Deathly Hallows', 'Fantasy', '2007-07-21', (SELECT AuthorId FROM dnbookstore.Authors WHERE FirstName = 'J.K.' AND LastName = 'Rowling'), 9.99);
