version: '3.8'
services:
  postgres:
    image: postgres:16.3
    container_name: dnbookstore_pgsql
    environment:
      POSTGRES_USER: dnbookstore_user
      POSTGRES_PASSWORD: dnbookstore_password
      POSTGRES_DB: dnbookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dnbookstore_network

networks:
  dnbookstore_network:
    driver: bridge

volumes:
  postgres_data:
